### ISSUE TITLE
Rename buttons in torrent screen to better reflect their behaviour

### ISSUE THREAD

**Issue by Invictaz** [LivingWithHippos/unchained-android#103]
Added a torrent via a torrent app. Instantly within seconds it shows "downloaded" with a button beneath it to download it. But it already has completed downloading?

Seems that this is a popular release that is cached on realdebrid and doesnt need additional downloading.

Button might need to be called "import" or "open folder"

![Screenshot_20210610-005452_Unchained](https://user-images.githubusercontent.com/20338545/121439890-1c730500-c987-11eb-96de-38f3c96e8392.jpg)

**Comment by LivingWithHippos** [comment]
While torrent are cached for a long time, downloads are not, they become invalid after a while. It is not possible to download a torrent directly anyway, you always have to pass through the download section (just like the website). "Downloads" is used in Unchained (like in real debird) not as the files downloaded to your phone but as the ones in the [download history section of real debrid](https://real-debrid.com/downloads). 

I think that for torrents with folders we could use "Open folder" since there is a folder screen now

**Comment by Invictaz** [comment]
Then the download on real debrid is like importing and download to phone is real download. 

Btw it opens the folder screen but the folder is not displayed in the download list.

**Comment by LivingWithHippos** [comment]
> Then the download on real debrid is like importing and download to phone is real download.

When you add a torrent on real debrid's website you can choose the files to be downloaded on their server (missing in the app for now as all files are downloaded). It's the only time you can choose it.

When you press on the unrestrict button on the torrent in real debrid's website it goes to the download section of real debrid and all the files you checked in the first step are transformed into actual downloads.

You can then choose which file to download by pressing into one of the  links provided

> Btw it opens the folder screen but the folder is not displayed in the download list.

This is how real debrid works, again, check the [download section](https://real-debrid.com/downloads) of your real debrid
