### ISSUE TITLE
Download button instantly crashes the app

### ISSUE THREAD

**Issue by Invictaz** [LivingWithHippos/unchained-android#104]
- Android 8.0
- Samsung A3 2017
- App on internal storage

Download button instantly crashes the app with no option to report the issue. 

Any idea to debug or to supply a log file?

**Comment by LivingWithHippos** [comment]
Fixed with [this commit
](https://github.com/LivingWithHippos/unchained-android/commit/50f9addf6f0e0417ca14e9512ee0992c5c9c63de)


> Any idea to debug or to supply a log file?

In cases like this I think you'd need to install a logcat app like [this one](https://f-droid.org/it/packages/com.dp.logcatapp/) and then use a pc (only a single time) to run via adb the command `adb shell pm grant com.dp.logcatappandroid.permission.READ_LOGS`

At this point you should be able to read all the logs from the app

**Comment by Invictaz** [comment]
@LivingWithHippos 

I remember that Logcat needed root permissions for deeper logs. Is that correct?

**Comment by LivingWithHippos** [comment]
Not sure about this particular case
