### ISSUE TITLE
[FEATURE REQUEST] Add "copy all" and "share all" options to folders view

### ISSUE THREAD

**Issue by Ravi9736** [LivingWithHippos/unchained-android#157]
Sometimes when i download a big file and i turn my internet connection off my download cancel automatically
So please add support for external download manager because it comes with many extra features like pause and resume and more

Edited:- I am talking about folders

**Comment by LivingWithHippos** [comment]
I suggest you to use a dedicated app, nothing can beat that. I personally use aria2app [Github](https://github.com/devgianlu/Aria2App) [Play Store](https://play.google.com/store/apps/details?id=com.gianlu.aria2app&hl=en&gl=US) [F Droid](https://f-droid.org/en/packages/com.gianlu.aria2app/)

I'll add a little external download library because I need that for downloading outside the internal memory
