### ISSUE TITLE
[FEATURE REQUEST] PWA app 

### ISSUE THREAD

**Issue by Mav3r1x** [LivingWithHippos/unchained-android#189]
This way it can be used on iOS in safari. What do you think?

**Comment by LivingWithHippos** [comment]
Well the technology for WPA is  completely different from the one used here for Android Native, so it would require me to rewrite definitely too much code/time (I made this project to learn Android so it's free and without ads and it's not bringing me any money "by design"). 

What I could do is use either [Kotlin Multiplatform](https://kotlinlang.org/docs/multiplatform.html) or [Kotlin Native](https://kotlinlang.org/docs/native-overview.html) to bring this app to desktops and iOS while sharing as much code as possible. 

I'm currently playing with kotlin multiplatform for a project so it's not impossible but it's definitely not on the radar for now.

**Comment by Mav3r1x** [comment]
Has there been any progress on this?

**Comment by LivingWithHippos** [comment]
Hello, a PWA would be something to write from zero and I don't have the time to support another project with a scope really similar to this
