### ISSUE TITLE
[FEATURE REQUEST] Support for Debrid cached torrents

### ISSUE THREAD

**Issue by Invictaz** [LivingWithHippos/unchained-android#205]
Support debrid cached torrents or indicate those that are directly streamable.

/torrents/instantAvailability/{hash}

**Comment by morpheasgr** [comment]
> Support debrid cached torrents or indicate those that are directly streamable.
> 
> /torrents/instantAvailability/{hash}

Cached torrents are already supported, that's the whole point of the app. Once something's been cached you can access it either for downloading purposes, either for viewing purposes.

Suggesting issue rename to "Add cache check (get hashes efficiently & lookup) for searches"

My thoughts on this: probably limit the max number of total items to queue and introduce cooldowns (and status caching with invalidation obviously) when the same host is selected for a search. Indicator and listing priority for instantly available results would also be cool, as in "cached items go to a top section, then get sorted by size descending).

**Comment by LivingWithHippos** [comment]
some notes

- a torrent may be only partially cached (for example a movie may have subtitles/trailer not cached)
- since torrent results are limited we can probably check for cache for all the search results
- caching occurr on real debird servers when torrent files are downloaded, there is no invalidation or caching choice on our own
- cached indicators/filtering/ordering should be added
- cache check on a torrent hash returns a list of cached files of that torrent

This probably need to wait for torrent file selection #94
