### ISSUE TITLE
[BUG] Issues with downloads on Android 14

### ISSUE THREAD

**Issue by LivingWithHippos** [LivingWithHippos/unchained-android#368]
- selecting a folder on the external sd does not work, it gets downloaded in the internal memory
- in some cases it also fails, possibly the issue is the same
- we observed that other download apps have the same issue so it's probably related to Android 14 (maybe also 13?) and not to Unchained

https://developer.android.com/about/versions/14/summary

**Comment by boognish-rising** [comment]
Not certain it's relevant but I've found, in addition to these observations, that a download is less likely to fail if you select "Open" rather than "Download." Failures still occur but at a much lower rate. Maybe 20% as opposed to nearly 100%. Very anecdotal, though and I can't speak for saving to external storage.

**Comment by LivingWithHippos** [comment]
> Not certain it's relevant but I've found, in addition to these observations, that a download is less likely to fail if you select "Open" rather than "Download." Failures still occur but at a much lower rate. Maybe 20% as opposed to nearly 100%. Very anecdotal, though and I can't speak for saving to external storage.

Which download manager have you selected in the settings? The system one or okhttp?
