### ISSUE TITLE
[Serious Bug] can see other people's torrent list

### ISSUE THREAD

**Issue by kaiteck** [LivingWithHippos/unchained-android#372]
In the app, torrent list can see other people's torrent. Because of this bug, I cant seem to find my uploaded torrent coz the list is too long. 

The issue happened around SGT 4pm today . It was working before that.

In my real debrid webpage, nothing is wrong. Ive refreshed rd api token so its not compromised. Download list doesnt show other people torrent list so this issue seems to be only on unchained side.

**To Reproduce**
1. Go to app
2. Click on downloads bottom tab
3. Click on torrents for the list

**Comment by kaiteck** [comment]
SGT 4pm time

**Comment by LivingWithHippos** [comment]
Hello and thanks for the report, there is no way for unchained to do this by itself since it just asks real debrid for the list. 


1. Did you set up something like stremio or kodi or some other programs using RD aside from unchained? 

2. Bug on real debrid side, check on their socials or on the real debrid subreddit if it happened to somebody else

3. I think on the real debrid website you can check for accesses so maybe try to match the timing. You should also go to the "devices" section and remove all the authorized options (you'll need to reconnect them)

**Comment by LivingWithHippos** [comment]
Also the download and the torrents list are 2 separated pages on real debrid, this is way it's also separated in unchained. Click on torrents on the top bar on the real debrid website

**Comment by kaiteck** [comment]
Real debrid announced database having issue
