### ISSUE TITLE
Make bottom navigation bar more consistent design with newer versions of android

### ISSUE THREAD

**Issue by oathzed** [LivingWithHippos/unchained-android#50]
See picture for example

![fds (1)](https://user-images.githubusercontent.com/52545913/94999058-693a4c80-056b-11eb-8645-6cd107bf12a9.png)

**Comment by LivingWithHippos** [comment]
You mean with no gap on the bottom?

**Comment by oathzed** [comment]
> You mean with no gap on the bottom?

Yeah so make it like the right image, so it takes the colour of the bottom tab bar

**Comment by LivingWithHippos** [comment]
Tutorial [here](https://developer.android.com/training/gestures/gesturenav) and [here](https://medium.com/androiddevelopers/gesture-navigation-going-edge-to-edge-812f62e4e83e), need more investigation. Since we only want to apply it to the bottom bar, it's possible to bypass this by creating a different `res/layout-v29/activity.xml` file with the transparent setting for the bottom navbar:

```xml
        <com.google.android.material.bottomnavigation.BottomNavigationView
            android:id="@+id/bottom_nav_view"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintLeft_toLeftOf="parent"
            app:layout_constraintRight_toRightOf="parent"
            app:backgroundTint="@android:color/transparent"
            app:menu="@menu/bottom_navigation_menu" />
```
