### ISSUE TITLE
Opening a download or a torrent and press back fast

### ISSUE THREAD

**Issue by oathzed** [LivingWithHippos/unchained-android#56]
open the lists tab and click on a torrent or a download, then press back really fast, it will blank black screen

**Comment by LivingWithHippos** [comment]
We'll need to re add the transitions since the looked good. The issue is probably that the transitions are too fast, check what Chris Banes[ has to say here](https://chris.banes.dev/2018/02/18/fragmented-transitions/):

> 
> Postpone
> 
> At this point I remembered something which my colleague, Nick Butcher, had mentioned to me in the past while he was writing transitions for Plaid. Specifically around having to postpone transitions until your views are ready (laid out, data loaded, etc).
> 
> So off I went and added postponing and starting to my fragments:

```kotlin
override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
  // View is created so postpone the transition
  postponeEnterTransition()

  viewModel.liveList.observe(this) {
    controller.setList(it)

    // Data is loaded so we're ready to start our transition
    startPostponedEnterTransition()
  }
}
```

> 
We have to do this for both the entering and exiting fragments so that both the enter (click) and the exit (back button) work as expected.
